//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdSubType
    {
        public AdSubType()
        {
            this.Advertisings = new HashSet<Advertising>();
            this.SubTypeCategories = new HashSet<SubTypeCategory>();
        }
    
        public int ID { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
    
        public virtual ICollection<Advertising> Advertisings { get; set; }
        public virtual ICollection<SubTypeCategory> SubTypeCategories { get; set; }
    }
}
