//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertising
    {
        public long ID { get; set; }
        public Nullable<int> EngineCapacity { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> ManufacturingYear { get; set; }
        public Nullable<bool> IsAutomaticTransmission { get; set; }
        public Nullable<bool> IsExchanged { get; set; }
        public Nullable<int> AdTypeID { get; set; }
        public Nullable<int> AdSubTypeID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<int> SProviderTypeID { get; set; }
    
        public virtual AdSubType AdSubType { get; set; }
        public virtual AdType AdType { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Model Model { get; set; }
        public virtual Region Region { get; set; }
        public virtual SProviderType SProviderType { get; set; }
    }
}
