//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyContactU
    {
        public int id { get; set; }
        public string ContactUs_Eng { get; set; }
        public string ContactUs_Ar { get; set; }
    }
}
