//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyProfile
    {
        public int id { get; set; }
        public string Company_Profile_Eng { get; set; }
        public string Company_Profile_Ar { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    }
}
