//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CPanelEntities : DbContext
    {
        public CPanelEntities()
            : base("name=CPanelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdSubType> AdSubTypes { get; set; }
        public virtual DbSet<AdType> AdTypes { get; set; }
        public virtual DbSet<Advertising> Advertisings { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CompanyAboutU> CompanyAboutUs { get; set; }
        public virtual DbSet<CompanyContactU> CompanyContactUs { get; set; }
        public virtual DbSet<CompanyProfile> CompanyProfiles { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<EmployeeData> EmployeeDatas { get; set; }
        public virtual DbSet<FileUpload> FileUploads { get; set; }
        public virtual DbSet<ImagesGallery> ImagesGalleries { get; set; }
        public virtual DbSet<LinkTable> LinkTables { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<SProviderType> SProviderTypes { get; set; }
        public virtual DbSet<SubTypeCategory> SubTypeCategories { get; set; }
        public virtual DbSet<WebSiteTable> WebSiteTables { get; set; }
    }
}
