//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeData
    {
        public EmployeeData()
        {
            this.FileUploads = new HashSet<FileUpload>();
        }
    
        public int Emp_id { get; set; }
        public string Emp_name { get; set; }
        public string Emp_Email { get; set; }
        public string Emp_Address { get; set; }
        public string Emp_Mobile { get; set; }
        public string Emp_Password { get; set; }
        public Nullable<bool> Emp_IsAdmin { get; set; }
    
        public virtual ICollection<FileUpload> FileUploads { get; set; }
    }
}
